#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:24
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.SImon.sivol.gn.v20200919|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'SHA256' 'e779e79d708cbb15aef334989b145d6bc8a6b61bf49438f514008ce25d825f74'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'SHA256' '78dc639930fb109d42365847295dda45c551cf29e30f649e12a47fae1cc24166'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'SHA256' '8e581dd4f190e21c50e656aeffb45788bb4b36e3e83f2fe97bbe0d1021b7e499'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'SHA256' '7d7bbf8cb8ea1fbacc6612f7dcf0fb3e010f27176e5f1cc9f5ec3426411d8acb'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'SHA256' '906340d946007029f4bc16d37cb88686c2ce520de27daeaa1899979e5e241e67'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'SHA256' '61352bb9d7dac4ba07049fe1419e55fe1cd9c8cc0f13a7ee99111c3f5b440f32'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'SHA256' '77376dddae62a66070b297d99974f3f5d583f6954d357131aa9fd58f25a63b77'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'SHA256' '30f0a8963d500a4648dc3d22ddd427c09691183e103d2148ca078dd619e279d1'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'SHA256' '0e22c4251c0d11873244aae01722c838b59b9307ca7f96fee979ff5b3ca094cf'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'SHA256' '52fd94adddd8a49b6892efc97537b7a0bef4cb51da6e761c7f9c2af33be52624'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'SHA256' '1b8c4632dc3a9f5e78171b220d142d15145a78953f3317f2f93cfd196692c5b2'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'SHA256' '0a1817815b78ef0c0da041ddf5585ecc617e522208abfe8b5675fb7b84c2afb0'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'SHA256' 'bcd5b6d89b020aec7a9ca52428d04de554492a1d77e5d4f2ccebf78ca2ffa365'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'SHA256' '0afa11efe906926140dae42a207d4c545e58a0f9bd17570635feb58fb1623439'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'SHA256' '6a05d975526a6bad7af528ade0775ad471a1a618e587341ff6a20c4961da85e2'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'SHA256' 'e8671e2bac365351f11121173d2b062661c1e14b0c7ebafa657c6cefa932f2be'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'SHA256' '511c1d121514145fe87f74f7809a47787511218c3ad40f9df80e7e0263d16b26'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'SHA256' '1bf1c847734e18296395ef9406b18590c9b9ec630fe0f86db560575feea63021'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'SHA256' '79087b1708ef67e0449051f71da43720dc6fd725ae6a46cc76d960e1964bf449'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'SHA256' '22add620f959c47f8209ca06e024a4a7c013096a2a15a56b5777631780048f5f'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'SHA256' 'd26a93b8dfcf1a99878b9576e0091c63cbdede7a031aa971031a9172429ba6ac'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'SHA256' '4ceacab4fd0debf257804de242ccd6895a9a2e41420ca7552c3ea1fcc3eee0e7'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'SHA256' '4a730a4d13c5192e03ede83d186d851e81e19b3409abfc37e1bc618fbb29aa9c'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'SHA256' 'f2dbab41d3189ef72e4c35479209b2e8d59178953f3d28139fc96f8da16d4c5b'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'SHA256' '9a9a2eb4097c492a645c3b596ca9cb654dbb00fed26d76294bbfc4c6cd6eb1c9'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'SHA256' '6e89911de1a5c026fad75189f61ad95ea5944f0237fa941599b53aff8d1da710'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'SHA256' '00b7a3415ea7413a5553d61162ef90e9973554db44a091ed1c0d06a025f63d46'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'SHA256' 'dd2c01ee4ae5ab2be8a34f3c02b4b8aeaab305071e3a88938e83dde98a12d780'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'SHA256' 'e8a0b0f8371055dbde60f691acbd030b3c10c1941f6b597035947be408736756'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'SHA256' 'c8ecd3024f68f5bcf1db41e57ce59f3e107172920fd880eb1c3e3466ca7a8722'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'SHA256' '6e0a9da48591299baf3cd9e9c1af1495feb0ef5ce1d09ea8f37abd4a50feba52'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'SHA256' '9cd8cd6ec34e5f5d3e0deb06a0bbd66db751973870bb0d809871aaec7a07d8a8'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'SHA256' 'ce6ef8689de028818ac1707bd5045b671a4a128526ec60c6e0f4eeed268c30ec'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'SHA256' '66668007582c2e74c47a791bc37708e0ec88a2b419f6ed2c68daba41aa207952'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'SHA256' 'f1c5499d5565474fdc55e182878f278da96322df102fc4773faf7c3a7605bca6'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'SHA256' '422f217571a374190592538c39e1554b74141af963e4a26aa0e2982f55ca25e3'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'SHA256' '3a932cf0bfb94c937e77feb6aea2c29ad7baff1183778a2098b6a22cd657afcb'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'SHA256' '6d387444a210b2eddf15f79cf1efff9421e40c62ee1b31cedaed1140313e4dd0'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'SHA256' '55f63a74c0b8d12225301bbffb004b033dfab8b2ef94f13c20aea6e6862e04b7'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'SHA256' '4bfea51cb297794066d12a5357201b0f1835d988b3d8bdea55aae9f012c019ac'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'SHA256' '376baebe57da351d21012c22ce209e8447f03526e475d51c5adde0121dc700cd'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'SHA256' '65e769f89a76c2d817975a965e23db0b2318e00951f1d42c9cd5433990acf889'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'SHA256' 'a57ba35f347f2309f36c2d2333f8833baa0968474e787437029dbd1088d1271a'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'SHA256' '1801cbaa6c452a1b95ecd1b9f5445c5c45a618e2ea6f73fc5d15887ad417e096'
'sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/SImon/sivol/gn/v20200919/sivol_SImon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'SHA256' 'f695824cbeec5b7d5fba22952f64faddd1c284db04d4544ddf74b9ffc66d07b0'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
