#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:59
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r132i1p1f1.Amon.hurs.gr.v20200412|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199501-199512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199501-199512.nc' 'SHA256' '2fdc049a0ebfa842932c7998f81f72fa46c702d3fd48dc491dba1c393e9ed394'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200601-200612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200601-200612.nc' 'SHA256' 'b274c5f3623e0c32eaeff7905b9b2a3c3f06f7c02972c2b267c749eaf2d548ba'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199101-199112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199101-199112.nc' 'SHA256' 'f5be8ce4991d554f7fec4c308bc71be99cc30a6471c04b19039b1734dda13989'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198601-198612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198601-198612.nc' 'SHA256' '5b4bf801cc0a873dbaf490169c3bdf993f841095ad3a8b5883d325feafe5e48e'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199701-199712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199701-199712.nc' 'SHA256' '3d517ad92d279f9e0df1e40d49302bf54ad85d520f33ad05f87ca1f8afe8ce4b'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200301-200312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200301-200312.nc' 'SHA256' 'f1c656924bf67722819394cfbf46446598dc129f5b8e8d3499ae48dba0fa7e32'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200801-200812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200801-200812.nc' 'SHA256' 'bf72e45dbabd1bfdf3dca2dbff8df371e625cf9be32299e45496129228c197cc'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199201-199212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199201-199212.nc' 'SHA256' '05090780ccc86fcd1a20cf8c0625c54dbe99641779a0796f8a096db0e9b7773f'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200701-200712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200701-200712.nc' 'SHA256' '2d0e168c042884d6ab0692a3097adce1ef4c7dc7dee7daa51c1294128648c61a'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197701-197712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197701-197712.nc' 'SHA256' '511a416712e9d9c8df72a64883f18c15dbf4d70d161e0a92613ff14580502732'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198401-198412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198401-198412.nc' 'SHA256' '541691bcf6e182deae3e2fabb080b540c422d65a6076a8cd16e1063d4dc0114e'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198801-198812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198801-198812.nc' 'SHA256' '0625d2e81da907a55b8bbeaf6f1a35a3f4100a9ad0ca4ac7c514cf94ae221972'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197601-197612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197601-197612.nc' 'SHA256' '007a630e4377525302eea6d4857226a1890b1d0c3eb86efb9bbb66e44d28f00f'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199801-199812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199801-199812.nc' 'SHA256' '245a8d6673e88a7d7a97df6afc66dd84f96dc358bed4a9ca7ecb4b2d9c4bb085'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201401-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201401-201412.nc' 'SHA256' '153b8a2fbfc5328e5f27e8a43da84cc721d88c515ddaa8ef728b634bf31879d0'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197001-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197001-197012.nc' 'SHA256' '5a526f889ccbf0f717fdcbcee9f6debeb636db47a309c7b1832253fc27b82384'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199001-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199001-199012.nc' 'SHA256' 'f195e15a126418fafb511864da97da6256786bcff76d1fc881829f0e85587c9b'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200501-200512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200501-200512.nc' 'SHA256' 'bc38a9a93998c93a0eef97f340117efbf3d1d034975bb7890cb50039cad699c1'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201301-201312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201301-201312.nc' 'SHA256' '95de3ce06eb8db4b062e0d5cab70929831e4ab5f60348d897fe48bdbc75d4117'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198101-198112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198101-198112.nc' 'SHA256' 'b06940b98db8ad6016a939aa229b1ea255a9b0adec849c657dbded383afcd63c'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198201-198212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198201-198212.nc' 'SHA256' 'e44da66a11831302cd441c5e2dee96e06d0b842f79eac14c3ce7acc21fd1dde3'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198501-198512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198501-198512.nc' 'SHA256' '39979c98e4670f6aa1b005bae04fdb087aa95f0728accb06f4833ead0d012e42'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197201-197212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197201-197212.nc' 'SHA256' 'fa7d75137827ab4c6f1df65e1dbaf7caab142c540a06763664d5415cd475b497'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199301-199312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199301-199312.nc' 'SHA256' '598a844ebc950d4ce6d0093e82c46942fa5ba0994a84ebfea26f0afade512b3c'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199901-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199901-199912.nc' 'SHA256' '1f55256589dee9e378a181feafa8bd3f1ce175a24c79ac33b58e245e886177fe'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201201-201212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201201-201212.nc' 'SHA256' '15b20ff836dfc339215517d60546b6ebda5212ce2475e1f2a4b76167973d51c2'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198301-198312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198301-198312.nc' 'SHA256' '485714c0d4b0a5e96e39980fa36e55ec2b6b194a7ac95afbdb41ed280b1456c2'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199401-199412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199401-199412.nc' 'SHA256' 'f983360c7302717c9e79edf332ebadd3f721c43c72cb489c996120b55829287e'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201101-201112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201101-201112.nc' 'SHA256' 'df10792fd67767d5d040ac4ba23953db17fb988c111e1afe5a4ee17fbe483210'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197301-197312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197301-197312.nc' 'SHA256' '8741a8fa8b0c398c075fbbc698be6d7beade40b799e674933c95ca78b00f4853'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198001-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198001-198012.nc' 'SHA256' '8adc4b9cc9540bcf4b75a50757f60852e27babfd8efa18add210d65093db1928'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200001-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200001-200012.nc' 'SHA256' 'e51a57921d97e578db0d977f3f0b4573dbe9605f615e053a35bcf878f5c50512'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200101-200112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200101-200112.nc' 'SHA256' 'cd61428afb5de7b5ad3f1ec057450a69648dfad01bf9381de2343a13f724dc5e'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197101-197112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197101-197112.nc' 'SHA256' 'ad259a0fb9b60a3af049d19d32e342a8e430cd4e167593a51bb437710e8ae75d'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197401-197412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197401-197412.nc' 'SHA256' 'cea8a4a5778251d71f0ec1a83f9f54c893d64d3c47af75c276211441472736cd'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197901-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197901-197912.nc' 'SHA256' 'e4da3bbebbe506272bef036da1d94603dbe93fcb5be59b32ff1fc2225594ba94'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198701-198712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198701-198712.nc' 'SHA256' 'cf689ef908b3be99031b21db436c9da036c368e24f8ab7acc12cf8a162fcda79'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200201-200212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200201-200212.nc' 'SHA256' 'd4197fad5f3be6a8a4aaead053bd28d6e32556ccad47fe7d7ec7448f6d276d2d'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200401-200412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200401-200412.nc' 'SHA256' '7b33449676098e5133a886cec49d2d65786a5404255f552a3fe2bf1568c1526f'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200901-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_200901-200912.nc' 'SHA256' 'c3598babd7b66bb29a3113750980cbc0243840faf3853018f4cff64bbfaf3575'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197501-197512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197501-197512.nc' 'SHA256' 'c77c7f2dd66b8bc2693eb7d1fb2672224ffe27e78f59f9b4633f07a36fce5bfd'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197801-197812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_197801-197812.nc' 'SHA256' '89010a2d764fb843f9f1e55bebee0068f0ff62977e391c519c9bb6a8c35ce68b'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199601-199612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_199601-199612.nc' 'SHA256' '388c79a55e31061047e8ca9be1f19396ddee37eb31ac4f61350807d681a6dd78'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201001-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_201001-201012.nc' 'SHA256' '44ea86bf2cbb0e74bfb010684e0b33a2eec4cc79ba68f378a6464861a7d34332'
'hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198901-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/hurs/gr/v20200412/hurs_Amon_EC-Earth3_historical_r132i1p1f1_gr_198901-198912.nc' 'SHA256' '82ce476945654c880c29548366e9392c521052e33d83fa06907887ef7ea50164'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
