#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:50
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r121i1p1f1.Amon.prsn.gr.v20200412|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197101-197112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197101-197112.nc' 'SHA256' 'a972b12674cebe4089e3e2bcb63a9361c9e78e6ce7a1d09c96742b135044d995'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197301-197312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197301-197312.nc' 'SHA256' 'fe366f7ab15eb721b3476f87e5c741bdaaac484104a204bff1214add4167ff49'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198201-198212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198201-198212.nc' 'SHA256' '14c462c6643d8f2a82a344b6f1141ed4d05de0d14d830ce99f6659a0514cda3a'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198601-198612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198601-198612.nc' 'SHA256' '651f3064a69749b0b729af0c31f203bdbf98df4a70c4477dd7fd3f140ea14600'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199001-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199001-199012.nc' 'SHA256' '92f87e85a3f045221d21dd4cfa5b38fdfac1942890e010ac390cf833190e759e'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199101-199112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199101-199112.nc' 'SHA256' '3778830f215fc54def5abf4a7eae8984f68cd19b02da679410fd70c68a2c8165'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200401-200412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200401-200412.nc' 'SHA256' '4800964cc1e25a9a378e36579804c54f2001d0038a0c15ba84be96eb7fc5e2be'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197201-197212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197201-197212.nc' 'SHA256' 'cf4f5b5ab6f9b119a73ad714e0c8ed1ccf4adc88da5062e7d3d43f88190ce0c6'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197901-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197901-197912.nc' 'SHA256' '3f5792db9901ba0af526088d6a26ab97fc7f85ae6821dcd071ccbb2fe05c6a1a'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199401-199412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199401-199412.nc' 'SHA256' '92117f1d922199939e3bf7e1775f5000870529da7000e71417a9b09c371b2860'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198101-198112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198101-198112.nc' 'SHA256' 'd419e920ba801febcda20b949e7da738e2e2e135cb5da90a4d7f81bca1b0821f'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198701-198712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198701-198712.nc' 'SHA256' '7c9970057d873f02a66fe386fd0eb81eb2a51d00a05c13cbf14cdb84dcfdf175'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200501-200512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200501-200512.nc' 'SHA256' '66b9405a204d61e0137dc92840fbccb22e588a67aae44afd104ec1a7a9b79850'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201401-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201401-201412.nc' 'SHA256' '2b04781a88f5702320f41071446ff79b61f68cfe05eb14441f366aee10799652'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197501-197512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197501-197512.nc' 'SHA256' '017ef0fa775779ad333ff1b0d74685e906d9200206daa58ce59b7d6c01f21f17'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198001-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198001-198012.nc' 'SHA256' 'f3c60fecd5f7c4ae105dc7e161f8c25ee4d9288dfc84edfbefb378890d43ee2c'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198901-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198901-198912.nc' 'SHA256' '2ea56aab70f7736c6eaf49a765de051c4a9a3ba3f90842cd4d23501362f826c5'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200101-200112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200101-200112.nc' 'SHA256' '545c0ba6f9182c02fd73fd5967255042e7900a3c8b4539b16c91670b1cdf74bf'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201101-201112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201101-201112.nc' 'SHA256' '9b4c5f107a905266f07f3bc6ab80d227c5acbdec319b95c76f6993051ca9cdc4'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197001-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197001-197012.nc' 'SHA256' '4820532dbe0b1a1d3702561d6f39aa1efa4176c458201197490a98eddbf46a2a'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197701-197712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197701-197712.nc' 'SHA256' 'f6b14739aa487a864ff0f978b8864d31942263d99d728ac5ba684e92c00e4f77'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200901-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200901-200912.nc' 'SHA256' '9e161e09a46eb7ecd8d4955bc0bfb70e4d8f37509b10cb37decf181292a7307f'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198401-198412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198401-198412.nc' 'SHA256' '51efd22ddb74102148e206210f6b6f3eec40c95deaa45c00baef3289d3ebf625'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198501-198512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198501-198512.nc' 'SHA256' '2935f0129d9b0d46f383a65190190a9f35e2fbcf909a1f79d8aa1be699707ce0'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200701-200712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200701-200712.nc' 'SHA256' '013a8596284cf62ed79e9858901cb0b90f4857b2c8a30383e68f178da211c319'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200801-200812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200801-200812.nc' 'SHA256' '225fad5bd4efa34b546307a04a96602fb5cf921d62b88af8c7be14d635dd88c0'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200001-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200001-200012.nc' 'SHA256' '90ed27e1c17d409359d3a34cb5b711ab29ebac68457c286abe4071d2534c058e'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200201-200212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200201-200212.nc' 'SHA256' 'e55da6030cd9a84e9bb4cb450c2c72348ac19f5a7e8e96f2174d1dd2160f760b'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200301-200312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200301-200312.nc' 'SHA256' '1bbe71146f41c3726a999e27bed11228f886c380800d36f8c830a6abb8145b93'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201301-201312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201301-201312.nc' 'SHA256' 'da3877d33be69f7cd56d6a9ee31b709f09a63a80200b41d5031ed0beb36014b8'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199501-199512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199501-199512.nc' 'SHA256' 'b714f991f2ab62ebac702236c0301aa66473b151c9d445970376837847405c9b'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199801-199812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199801-199812.nc' 'SHA256' '52c8dcca858468df96455729c3b22ec08f70339f6f2fb343f81d9a196b7ea395'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201001-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201001-201012.nc' 'SHA256' 'c52e02b01d87168f899db7ba023aba885b964b320772132e108732723c2cb23f'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197801-197812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197801-197812.nc' 'SHA256' 'a394674211f9f9bd36ca0e29c04a297a8d5fbb32919b63d790e977210c2481da'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198301-198312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198301-198312.nc' 'SHA256' '0a9e1d5c02dfef8ce50e04643a70b7ca5a103e93da7b2f518d78a571ecc90706'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198801-198812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_198801-198812.nc' 'SHA256' '066a05ec0bd7b52047e38d6bc3b1fbda8582e57d550c0a1d84f5b947a4078b46'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197401-197412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197401-197412.nc' 'SHA256' '1d2a0084e841afe883f6c1e7849f64af020224e249052266addc932a4e988b50'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197601-197612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_197601-197612.nc' 'SHA256' 'fab22eab5ebb78b01dadfea9154651cc96f8a12027440b817b0aec751384d2d5'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199201-199212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199201-199212.nc' 'SHA256' '0d04c0b30976bb32b72eeef6f3d4cc249b074c177d1db94884c11ae98fb555a3'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199601-199612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199601-199612.nc' 'SHA256' '29b654a9c828c2efe562b677a76c612a50d8b5877b51620d7add72cd2fa425d8'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200601-200612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_200601-200612.nc' 'SHA256' 'dc35f1792a4ccbbc0576741bf2769e342af4d9af9baf1c82904f10f038716d8c'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201201-201212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_201201-201212.nc' 'SHA256' '1494ef9d3c8fc65eb9289928f7fb9524962e991ef77d13df23478d7180fa5107'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199301-199312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199301-199312.nc' 'SHA256' 'fa10aa230ae4e09b163eb197ba10f2ba64f83337f7367b86783d4c975dfa399b'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199901-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199901-199912.nc' 'SHA256' '1fe622806f6bad94097e6939625b9147f73c60bd036c6a52068e4c020d2c5e38'
'prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199701-199712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/prsn/gr/v20200412/prsn_Amon_EC-Earth3_historical_r121i1p1f1_gr_199701-199712.nc' 'SHA256' 'c7114385b53150f96f6d2f0f71dcb3503d06a99ad26866963dce00b07620561a'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
