#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:54:09
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r132i1p1f1.Amon.huss.gr.v20200412|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199901-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199901-199912.nc' 'SHA256' 'dfaf9bd7b20a3bb82c9235958a9c1be115f18a1ee35f82272ceafee8b51a7699'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201101-201112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201101-201112.nc' 'SHA256' '0beab2dccf24564987951bddb320dde23f270086ddfa766a2aec7b635881d68b'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197501-197512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197501-197512.nc' 'SHA256' '41b6f0a8b5dffac080a252264572f1fd5694e87ef4a74856bc13541f6211c19d'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198201-198212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198201-198212.nc' 'SHA256' '0e228c5adc1730d1d12bcffa257a037bde46e5dcfeec0019cba5414d1382f72b'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199601-199612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199601-199612.nc' 'SHA256' '025029a97fcf4dfb9ad56fb63dfe912c05390c349e9600fc096929ead4009298'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199801-199812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199801-199812.nc' 'SHA256' 'e8f362da3b5dee7424ec7653a49aa386771e952230ae86dc84514c2db148f5b0'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201201-201212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201201-201212.nc' 'SHA256' 'cdb550705789189a3815f29dfc5379d9809f770654dffbc7ca69a139eac3170c'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197101-197112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197101-197112.nc' 'SHA256' 'a80f56285294645bbfb624958753ff01f1c1063a6d7313a5c22b9b4939ca54db'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199401-199412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199401-199412.nc' 'SHA256' 'e77de7c2d0a397beb039ae18f153e01547b71058b6bb05fc6d4c235d9a893f24'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200001-200012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200001-200012.nc' 'SHA256' '1f85ab25b9b2549b9508b5cf6409ebf6ab6ca205e8a8b2feb02a7d4719ec7c18'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199301-199312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199301-199312.nc' 'SHA256' 'bb756b07cafa6f79ae517f20df44fdc34eda1cbc34cdc0b663e771f279bc9f99'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200101-200112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200101-200112.nc' 'SHA256' '5fd1b75ad8220a2782a620c60c67bd823befd7ca9d07feb4a34f8577bfaf768b'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197401-197412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197401-197412.nc' 'SHA256' '495ed8e8bc8b7244921f0d1abb659d6b2b1d015938916ee6d5dbf6763bc94cf2'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197701-197712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197701-197712.nc' 'SHA256' '01312e18ca5a6592f6a011e7fd0d02b5f749b6357c94e9dec36c238e6b040055'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200201-200212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200201-200212.nc' 'SHA256' '39e04a507e864db0ad757c7508560fed34d56c57cf10cec5c0f8ac3e34778da4'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197201-197212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197201-197212.nc' 'SHA256' 'ef9209b2d421c177cc4989ab8b5575f7e36ef48fea5b5176bc31f61de1d4f9b1'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197801-197812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197801-197812.nc' 'SHA256' '458f1202339d7c04dc68416714aa5cdf81e71d17ed8604df5476117eda937c5b'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197901-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197901-197912.nc' 'SHA256' '51762a3b8b6abc7f732ba8082517d4b1c97c21ff97bfd512aa6fc41bb570e969'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199001-199012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199001-199012.nc' 'SHA256' 'd6076920e2b0de516134c52049aa3b98943e00b60b39da989a44229fd676beb2'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200501-200512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200501-200512.nc' 'SHA256' '06c4e9b696effe17155b15ac308de47bcee0e9138ae45577d28c73c1036294ef'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200801-200812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200801-200812.nc' 'SHA256' '50a56e7d85d65f163f2fd33c051a1e791ee668805af5544e558946fed338cd6b'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201001-201012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201001-201012.nc' 'SHA256' '8864807cb8e1ab7faa6e2b511b74fe3f03dbb3876230a223366fe8b0e766d113'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199201-199212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199201-199212.nc' 'SHA256' 'b6b533f185c49fdee20654a726bf44ea53a3874c7b1ada9274523c327e668c35'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200301-200312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200301-200312.nc' 'SHA256' 'd86d0da6a40fbbc524154e098a04e07e08652479308bb77b3c156a8dfd37065d'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200901-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200901-200912.nc' 'SHA256' 'cbc2cc7deb18c6394070384511bf9d53cdcd58e6dcd80732b9fec5f1f8ac5ac7'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201401-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201401-201412.nc' 'SHA256' '06a403bb84e12189d9093f283c58a8a2b7cf5a89bb7ad6c4ec11056d4e9987ae'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198601-198612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198601-198612.nc' 'SHA256' 'c940b45283df73a27d7cdea5cb2bd3cdecf17f3a0c9cb4205328e7cdc423aa4c'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198701-198712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198701-198712.nc' 'SHA256' 'e305e8aef1bdc8a209424802c0526cb1fc4343728a9358c74e8b7bf4f77f65d5'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200401-200412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200401-200412.nc' 'SHA256' '3f398b65b82b90e844fc10b7337575d023120af25b692d2c78fb215c2179b247'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198501-198512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198501-198512.nc' 'SHA256' '7e700a1427ba918ac7c9b2b8e86a7c92451e26ba24b87f02bb187b320c569c3d'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198801-198812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198801-198812.nc' 'SHA256' '719ed6378d181ffb1dd36b3439206cff8184a9ea1d82f1677eb5c6e8f52aec8f'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199501-199512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199501-199512.nc' 'SHA256' 'f7b498f3d0e3a80a65ac9a88756e127a555f38353858afa053ee0c573de45c3f'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199701-199712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199701-199712.nc' 'SHA256' '4d192c1a3325478d2d545fe7aa9916b286ac1d5011038e9d0437e72d797dcc57'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200701-200712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200701-200712.nc' 'SHA256' 'ea492283c645ace7c42343de6b09faf96aeecf75b9220a8415818adc582f71d3'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201301-201312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_201301-201312.nc' 'SHA256' 'a75dbbe0fb2d29fd4493265122f562e66d29f886522ce7d3f2def4267f09c3da'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197001-197012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197001-197012.nc' 'SHA256' '4f645809b949dd60b2254c3f657139610d5b45a9b9a29dbfeddb380978e143ec'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197601-197612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197601-197612.nc' 'SHA256' '988812cf7cf5c05f65c406b9a2e3560a8414b22f5cf39245e7f2c55d31c4afa9'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198001-198012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198001-198012.nc' 'SHA256' 'ea1980a816cbe109016a8317db5dd9e3d2a62b51b14b361e68dd53f2eaf4836e'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198101-198112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198101-198112.nc' 'SHA256' 'e47e5cfb777b3df6dcad41205ed45c21e1a9f9b32a8ebf01a1f99c42f648fb0f'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198401-198412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198401-198412.nc' 'SHA256' '88440e84e5ce925152cc7c903ac34e65e5d30a6d8bba5139c874973b14f38544'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198301-198312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198301-198312.nc' 'SHA256' 'cdbe81f5cd708246a44587b1845fe1e10ed1ca8ba2c465104cd2f3e2301e1b44'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199101-199112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_199101-199112.nc' 'SHA256' 'd93ec443daa3f63b4ff10b9a85594bbd7a178d3ec6460346fbe86d46db8db241'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197301-197312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_197301-197312.nc' 'SHA256' '4ca73944e4a611cd79f80c4715f75631f67fc594621cfcc55de01995b439c184'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198901-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_198901-198912.nc' 'SHA256' '1f99a291d381115b8681c3f5e29ebfe5c19cedbb67bc08a7eb5656079990f319'
'huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200601-200612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r132i1p1f1/Amon/huss/gr/v20200412/huss_Amon_EC-Earth3_historical_r132i1p1f1_gr_200601-200612.nc' 'SHA256' '11ef7c4e8f02bfaa8056924d505560eb1b3cfaf75879be734ee8129d3ddb75c0'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
