#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:09
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.Omon.hfx.gn.v20200919|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'SHA256' '6439f846f1e5cf0c2b6da0f8320329410e13f3ed307219f3344a7a70acc0444f'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'SHA256' 'ea8f7054c8c22aad54182f0f5b93ff16aabd4a1e6957970d50464d5a8d88d0b7'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'SHA256' '86c61c78a2ba421e39956a148ebf597fb7c87cf14f20371dc00f32dc397fbf42'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'SHA256' 'beb79fc2aa36604ee9a7705a8099ba2199d05ff6cc72547afd6b3ffb8ce601d3'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'SHA256' '149e22fa5f999c3e5254957e4e7f68cfa8e6c0af7b180c508883fb7b489187e6'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'SHA256' '13e5f5fa78aa417eb483071a7cf180422155c570d83c372695defc738309c7f0'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'SHA256' 'a90649ecd5df9031a7c59e477560352833611935e79c4c33343ff4d9de3e9329'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'SHA256' 'bb5faa8f9304a1fca1820fa25b18a89a75b7714996347f80c900e737d8c519d4'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'SHA256' '76557891dee2fa777af28065959411fb4fbbade91a911611d63e78a283bd2af4'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'SHA256' 'b770b58da6618d3af748d76dbe9ff778cffe87492b39a4a6c2a70797fb1dba6c'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'SHA256' 'faed0cad9226d123199f75ac1fb9ca5eae6656a4ffc0a1801727893e0f479e8d'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'SHA256' '86d22a4b7ee8534b95a763b076f032414ad66cccc8bc4d0d1cd6df8103893c66'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'SHA256' 'a3c0fb8d751994ce1c94393ebf01b1bffe62ab5f1095f184c0fcc47f5003ce15'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'SHA256' '672213fa81ddc1bde6554900add8004d30cdbf0b8807df955a3e21358c087d59'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'SHA256' 'd3c9b84b533efcc47c84351ffed5dea409ebf04d2281dd588ab0c9dd24d1a2cc'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'SHA256' 'faac260aeaaa9d056299a15147e22edfcfc98e394168d09e0a627e2cebcf9836'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'SHA256' 'db4848098ee1b00e9fd4c3c0e014ce9a0eab6b61882fe764f681718c7c93cd86'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'SHA256' '55094c89a065ec5d586b8ce2a0ea0705821f1c07f48d156356921f78d9bf43e3'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'SHA256' '0f04916c4968f8cf7ed286a15d96eb3d5f5f19044d6bb87a539c3f35d32aa755'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'SHA256' '2a1294b822f1d67ad831c9db21d43429530f4f7130ba0ec985a70f93d679677f'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'SHA256' 'bd6cf586df4c9d03c5d44ab8cb4e613ca6cf5461a50db541c022d8a52c2878cb'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'SHA256' '71928583872a1f5a498aee12f216d44897309d4e8f4916028b485ed9298d6066'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'SHA256' 'f2ac028b489d718b7d37152c6415e84bd721eb4c0250d794347166ee6d2920dd'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'SHA256' '8397af465fbf5f8080859a4e6da33ceb039b800027e9d42e798471b7f95121e1'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'SHA256' 'b48de288c569ef578804b282a3cc94a9097c7faa0d019536266f06f86ad825ed'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'SHA256' 'faee32966800dad5d5fcee5b4370bed21b8d9cc16db0fe7cddd2e23abf0c01fa'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'SHA256' 'df1b51a0792403487bf9c27a4977090e2cc4b3e2b3080ca2bc6f5d6ffd121eb6'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'SHA256' '6710cadd2dc5b55a8079381610d30cb7b6dd73fa861435380add31466a687c98'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'SHA256' '3880ea94edbe0ab2500bb10c6449f2ce46f05e158e725842f696b5e6d424cc3a'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'SHA256' 'ea4b7cc09131546a08d7bac98f945dd254f83c4bd91bdad999e6a92bab71c848'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'SHA256' 'c474b155d1b0ddf6313a395fd6f706c979fc946f13a42145adcfd1680ace3335'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'SHA256' '9870d460baf8cc9073d1e50c5f8c9e0dedcf37b26af439e3d989fbe59b2c21be'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'SHA256' '8190f7e7f4c4dfe247f7bbffe3961ae63551ee3a7470d20b9bd4ef5e8b0fbea4'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'SHA256' 'f2a3ccc8a77827148958b8285aee6ec90b51e18ab747d6206843030d21ef72de'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'SHA256' 'd2dedef1ee71269b65f151b5eef2151bee6a6a1863bfc1bca9ca67c2956f6abd'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'SHA256' 'e6204ebb02dca6ed5e3a0277d2b23fe66a805932c0b38562219945ececd9c24c'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'SHA256' '6e589bf8d81c976acef31045fbe4a4a7806787683635989c201e337f3af825d3'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'SHA256' 'fed123af66825dbe98fc67fc5c326f96b3ecd970ab940f5d6f0ca28478a6cbdc'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'SHA256' '48e04e15aa4a98155a79e2ab1fff08f989f0479ce7aa1f0f8dbc8897e4cba5fc'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'SHA256' 'fcb8191dd9320ddcbb092695db126f9066ff7d10d792cee15174bda52199f401'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'SHA256' '02a0c7b984c5137161fc0ca00a094e01034624ed34887d82a2bb70586156bba3'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'SHA256' '53152aeacbcd2a637ca28cdee48869ac063ad815109b07e1b1ffe5281a63d751'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'SHA256' '0ec4dddeeca606951e437de27677974b349c94116e1c90ec46dc926a38209e18'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'SHA256' 'a87813d296eeb5791d48e46fccdedfa06a928760ee9d3f36efc2c336824ce0af'
'hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/hfx/gn/v20200919/hfx_Omon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'SHA256' 'f84a4ea76e1ef7c95d6a27a8dc15bccb76639e65e02b322ba070573c554d52e9'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
