#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:32
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.day.vas.gr.v20200412|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19700101-19701231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19700101-19701231.nc' 'SHA256' '298dfd9fa4d8cc9c9a1f22669a2caedf3b163454110b76647b943eea7c48459d'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19920101-19921231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19920101-19921231.nc' 'SHA256' 'f6d70aa35fef4698ede772b742855130ccedef9a9a370e6a61ce5a36d72666d7'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19950101-19951231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19950101-19951231.nc' 'SHA256' '6aefac9728efec1d9ad3371bb58905613b9d408994eabb2a234a796e12bd62ac'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20060101-20061231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20060101-20061231.nc' 'SHA256' 'ecd88905f490d5020cd0c2a930a53a1cbb513223c0c07130d8ce3dfdd353794c'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19990101-19991231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19990101-19991231.nc' 'SHA256' 'ed235df7408dd94727719354bf32532db0341e9ecbdacfb845e6be9d02baa220'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19730101-19731231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19730101-19731231.nc' 'SHA256' '35c9666a4320af8b4dda3bb97a3e8be8291a324fc72777a6c452483c3747b8b7'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19770101-19771231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19770101-19771231.nc' 'SHA256' 'bd191e6ab0e0e28a56ffedf54577eb95f45503cf35f996f8764beb251dd18f40'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19740101-19741231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19740101-19741231.nc' 'SHA256' '1f6d813eb7a64b76a87c0b319fe57dd056d1bc9d5edea6f223cd2b90af2d6632'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20030101-20031231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20030101-20031231.nc' 'SHA256' '4b8917cdeb863a4dec086736623580a87d6b5e43ba52942fceee5b266921eb96'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19960101-19961231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19960101-19961231.nc' 'SHA256' '81913061a8281af2936e91d58221969cae6521039de3d5293ef34420b3dac97c'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20130101-20131231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20130101-20131231.nc' 'SHA256' 'eab1200a230cd5557926a89753a0c16867e48074a940eeb80608f852067fe53e'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19850101-19851231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19850101-19851231.nc' 'SHA256' 'aec2952253a7a6d7af5eb4234c64f128cb54158e7dbdc9bfe6761cf03b4437a1'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19980101-19981231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19980101-19981231.nc' 'SHA256' 'bc55738620457135c84055992cbd950516bf21cb0586c6160dc56f4703e70588'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20000101-20001231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20000101-20001231.nc' 'SHA256' 'd1e62338845feb3276283531a647d045948736319af7e6e1707d59e4631fea13'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20080101-20081231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20080101-20081231.nc' 'SHA256' '89f982cfea5373180f742289e32b383c95f6193271e8f42b525ca1115570bb8c'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19760101-19761231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19760101-19761231.nc' 'SHA256' '8d8cff1e6d829c88c324b86a32525f0e90e9a6bbece59bfbe9cd2464108d1cab'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19840101-19841231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19840101-19841231.nc' 'SHA256' 'e3eb845bf0f25744a58f08708693f733f4cb4a55fd284839ee7e05da7a7406ce'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19870101-19871231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19870101-19871231.nc' 'SHA256' '33d651830e19c694d1d56c9bbbd164e670985efb582109364d032751deced4e2'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19970101-19971231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19970101-19971231.nc' 'SHA256' '295642f2c44f6b29a09368fc2f9a422fb066f332a1df0210c708e5ad628a1c2c'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20020101-20021231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20020101-20021231.nc' 'SHA256' 'e6a00c54cb41ec57f58429324df6aee0ef4aee747454a4c466398b47c7c2789b'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20050101-20051231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20050101-20051231.nc' 'SHA256' 'af907abacc50b0e0a3692d8ee036094fcdb6b6057790dae378a7f856c11d21a8'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19820101-19821231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19820101-19821231.nc' 'SHA256' '2fd6b82342bcd1721262ca198fe802661422d774052672ab1076468929e00665'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20070101-20071231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20070101-20071231.nc' 'SHA256' '7dd9149d35ba434f4ad05118170262a876b8e4fc5624542e6a93bb8ce38bf9ac'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20140101-20141231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20140101-20141231.nc' 'SHA256' 'ca16a796946bbeba0b650fa522b9b0d0e44712dd2023403a429d94ef0e298a03'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20110101-20111231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20110101-20111231.nc' 'SHA256' '420f831ed98515ce79907503a222b90820cb33dc780171c8d69ddda6b776b4a3'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19940101-19941231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19940101-19941231.nc' 'SHA256' 'd5f3d46f983221576c49f180e743b1138868b8260cdade192d6935549bd83a5d'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20040101-20041231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20040101-20041231.nc' 'SHA256' '6c44cf0077141bf2df4151e783d1317f140e719d859d9c6e158355120d7af699'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19750101-19751231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19750101-19751231.nc' 'SHA256' '993d6f886f83d966f99865ac844445502e32ca75367692027702b2e59720c70e'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19800101-19801231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19800101-19801231.nc' 'SHA256' '4e31e17f6fbff8a826f4fa1988ab236899e9505dc6c9dde859d8f0c5708bf836'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19860101-19861231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19860101-19861231.nc' 'SHA256' 'ca599db8fa9a9288492759104e04c9608ffde44463af5db1f8f09c297a6f5a2a'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20090101-20091231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20090101-20091231.nc' 'SHA256' '01a7c44c3863f93e80e19f543686ee470c54eead361c97091cfca981cf95c1cb'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20100101-20101231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20100101-20101231.nc' 'SHA256' '5cda33509e22a640936cdf4c4386f80aaabd1590a23cf1d905eb42f83e16628c'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20120101-20121231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20120101-20121231.nc' 'SHA256' 'e1d904f7d78ed3edba5ef8abaa23915518812669dc88caef3d0f354cdba72503'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19780101-19781231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19780101-19781231.nc' 'SHA256' '46d524f1bdd0b61e9091bf7c7af7ea2ffe8a27e2c99fa7a6d7c4c98e520210e8'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19830101-19831231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19830101-19831231.nc' 'SHA256' '4224665c87145806ba34c5f950657e73d1040971fd661d5d6c6e74157c79783a'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19930101-19931231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19930101-19931231.nc' 'SHA256' 'cf9950af061965c38f757cfd4512e3e5e26a99afc28ac2c5e6d383159c1b2f79'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19720101-19721231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19720101-19721231.nc' 'SHA256' '5980110297ee01defe8d4d8765d7a761aa4b52756d08b000cbe260b73e31ccf4'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19880101-19881231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19880101-19881231.nc' 'SHA256' '760dfeb109330645421a7493d43ac331832dac07d3009af7e070398dc5be9743'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19890101-19891231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19890101-19891231.nc' 'SHA256' '201001abef71f56dfd859590fb5f95fcbfb7982b96a9cc0f8282a1ea32e1294b'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_20010101-20011231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_20010101-20011231.nc' 'SHA256' 'f91214221c082ce0e3826a7f6139d813cc4c67346f070b84374b45aee02c2659'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19710101-19711231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19710101-19711231.nc' 'SHA256' 'd13987d0d47f7f392797b559fc10b056086347be1dbd032217bbad92db09039b'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19790101-19791231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19790101-19791231.nc' 'SHA256' 'af8e6701c712d9986b609b958564876bcfeefa61df6a9690124634cbbde78d94'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19810101-19811231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19810101-19811231.nc' 'SHA256' '2816ff33f36f8e9ee6c8c8dfbbae8f2a384adb7d82a8d0e45f91beb13ec09725'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19900101-19901231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19900101-19901231.nc' 'SHA256' 'f6a10da25eda8067221cce4658fbb2a0767172beef614e754b26834e9e5dc4ee'
'vas_day_EC-Earth3_historical_r120i1p1f1_gr_19910101-19911231.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/day/vas/gr/v20200412/vas_day_EC-Earth3_historical_r120i1p1f1_gr_19910101-19911231.nc' 'SHA256' '825b4d5b657ab03fdf80d20c014c477e8b1660b4902060a22b8fbea7565ce450'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
