#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:01
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.Amon.tasmin.gr.v20200412|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197001-197012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197001-197012.nc' 'SHA256' '576e8f870d288ae5bd5c43a0ae8f280961ab66144f29b184e23f4c9b606e41ef'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197401-197412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197401-197412.nc' 'SHA256' '97de782837426f531cd0b61c3201e0858e6d159d646b6a8ab45742b515719d6a'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198501-198512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198501-198512.nc' 'SHA256' '14cb304769bf618ab1108aedb4e606703a40a0eb9a3e2c419acd026628d4f167'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199201-199212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199201-199212.nc' 'SHA256' '4910160a4b19d5f4a04c6872d2f7e65e1ceafa1c61883c014f6dd4df5e52ee1c'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199801-199812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199801-199812.nc' 'SHA256' '5dda62fd59eb29d49a6e50d3ad21bfd5789cbe61249e0a8d7f634cecc10de951'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198801-198812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198801-198812.nc' 'SHA256' 'bf5191dba5e4f152a1eec6ee7e3a49a676538d1798d6e8af5dbfef973e135ef1'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200001-200012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200001-200012.nc' 'SHA256' '05fa4087fa4c75bd1984b7eb9fbda005a61c973cd9f5d2813e4ec4ff8d533b1b'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197501-197512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197501-197512.nc' 'SHA256' 'f9b85f027b8fd3a5e00bf84c8b6ede81c3ba594cd08ccfeead6a13b2bbb746e0'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199101-199112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199101-199112.nc' 'SHA256' 'c4bd28d0a3798c2d262d6d830d18e7f531a885d51fc3e18de780fa7bb43e2e44'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199501-199512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199501-199512.nc' 'SHA256' '58820797f9869a696e0efcab8cb5d9c188d06481a6eed93646ce8d005f46ea17'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199901-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199901-199912.nc' 'SHA256' '333f6cde295e827bcfdf042e168c05e7cb465a0a599e2a2023d84b8fefe22ea1'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200201-200212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200201-200212.nc' 'SHA256' '19cfd9e5ef119b25df6b7dbea1b745a86ff5646af333d91b55681976a9d9b392'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200801-200812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200801-200812.nc' 'SHA256' '21e8f7a03bb77d43f3c57189974c859fc4c9b256a44363e2530b8607cd7a774a'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201101-201112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201101-201112.nc' 'SHA256' '7c3c358d66c15563093f1e5198f0d2ab678db48ca57a56df740cfa3a31cc9f94'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197101-197112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197101-197112.nc' 'SHA256' 'a2ca73bb519eb2a585b89aa3d47e9d8c6b448e658bc0619e51dc259f1e9c2f45'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197201-197212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197201-197212.nc' 'SHA256' '0eb6aa27a78de7c8ce7260ddabb5700e74b2d3e6ee65a253c084593f8d47f93d'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197901-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197901-197912.nc' 'SHA256' 'fb5982555ba69052ed8d1fcbf56e67ff4be770bef20fae22ad63cd4aafd5c855'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201001-201012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201001-201012.nc' 'SHA256' '1ede2d3862bbe4356b9a67d41d2f31394f5442dacc2e50bccb63aaff7b52daed'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200301-200312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200301-200312.nc' 'SHA256' '8b79d07bbad03aeaeeae8765b3e9b95d55609a88664da3e893242d1cdbf62fc3'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200701-200712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200701-200712.nc' 'SHA256' '5f9cc30751cdc927ee2e6af4b130b23f543c90588a139a75f6686b88940c705a'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199001-199012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199001-199012.nc' 'SHA256' '848131c8833f9f518e6d86daa823f7185ce560bee812b1389a7e54c407a40baf'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199401-199412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199401-199412.nc' 'SHA256' 'af7e77f1f8a6cec6327328ecb0e34d2b148c21b33f2dcfd281e241056e22e8c6'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201401-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201401-201412.nc' 'SHA256' '3372d95b3ceb66f7144353d8caa58749b576e478e57fcd2a896d290c63370772'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198001-198012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198001-198012.nc' 'SHA256' '28694501edfd9f7a17753e1b3b5449f69da3aa68d9c5cf75a88f922a7dcf6757'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198701-198712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198701-198712.nc' 'SHA256' 'a38233e56195f276f77e8117e7358c7ffc81bef8bc8662bf99219227eed22cf4'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200601-200612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200601-200612.nc' 'SHA256' '4cfd846aeff45894f438cd1c7ce8d269c3d21ec9108cd38f043767b4a0b71e7e'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197601-197612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197601-197612.nc' 'SHA256' '65150950ced70d9e9c7f07df7063a08622ffb134d00ac65462a904c562be3cf1'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198401-198412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198401-198412.nc' 'SHA256' '48a99b61b33c36b39669fd54b688bcd0cce703e14e4e42664a3431b603c6b34d'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200101-200112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200101-200112.nc' 'SHA256' '0aad410f5a56a8e85727d90deaf52d52cff9f0623308f2bad08634dea188ac95'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200401-200412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200401-200412.nc' 'SHA256' 'c4781b7d0771aa379e9ade0e022668e6485aedf4a32968bae8cc451ca5719671'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198901-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198901-198912.nc' 'SHA256' '964c0e1c4876d58b31732a8075715038ac4ccda3e09ec0ff438aac2fc30d7262'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197301-197312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197301-197312.nc' 'SHA256' 'bde9608dff014681f38f7c7c1b46d587708be64c3a0c1de2cfce5d0f7a06518c'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200501-200512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200501-200512.nc' 'SHA256' 'e777325c92d44814f28251cee7a89e84b447385f6c7e97a0501512c86b24616f'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198201-198212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198201-198212.nc' 'SHA256' '2a5ff3370946f5dc827f8013871ec5455cb2fb6d4d8314654deb7fb43e0c1a95'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199701-199712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199701-199712.nc' 'SHA256' '79ec03b27c813ad0e314955402b40c8afbfa1640532e4d93ca38084719de6fff'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198101-198112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198101-198112.nc' 'SHA256' 'e63042e54e393a276fdc0e043a2628a266c87cfd59a22440f773b06faec155ff'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198301-198312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198301-198312.nc' 'SHA256' '9f6ec595a4703fd6219e9cb28fd78ea696746c3da2800f4d78dd4bebff5ff68a'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199601-199612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199601-199612.nc' 'SHA256' '26f50d75cc3a24a68c2c9b799e191211a73ef18a11e83513899215d1d3c40bfc'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200901-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_200901-200912.nc' 'SHA256' '88b1759274777be1c9bba736a06489cad33aef0aa0c80652b39095eb8d9145d9'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201201-201212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201201-201212.nc' 'SHA256' 'ad124cf2d23da5830d9c3a83aeb2111e0b7931d62633e0a06eea65d71258219d'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197701-197712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197701-197712.nc' 'SHA256' 'bde6bdb2745fed774eaf16942cedccaf1645d98dadf9a61987eb3c40736ebc77'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198601-198612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_198601-198612.nc' 'SHA256' '92cf0ba760b93b2b238754979ce45839fdbbd279102f1dff12ebbeef37a0699e'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199301-199312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_199301-199312.nc' 'SHA256' 'd0642376f962743ce925aa7ac12f1cce127337f346756480e01a33359499e35b'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197801-197812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_197801-197812.nc' 'SHA256' '28bf2558ed7f809fb7d98f6e314add3ee4be9048ef290d12a3383fa74690dbc6'
'tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201301-201312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/tasmin/gr/v20200412/tasmin_Amon_EC-Earth3_historical_r120i1p1f1_gr_201301-201312.nc' 'SHA256' '83addca532bcaaab934ce3ee46a0e0c175b5f5089306620f5bfb6c2a11091f2f'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
