#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:43
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r121i1p1f1.Amon.hus.gr.v20200412|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198001-198012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198001-198012.nc' 'SHA256' 'a7de6af2f25fb1531bcc0c0c1021bd17fd88be1f768d7e64cfca21e6423ca7b5'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199101-199112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199101-199112.nc' 'SHA256' 'a0d5daccf66f297ac2091d04faa7c65b95f286e2a714c8841278327656578775'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200801-200812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200801-200812.nc' 'SHA256' '574443657b07c049d7b205730b53c1f0ca50adb19dbe9d8799299416b0888603'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197401-197412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197401-197412.nc' 'SHA256' '5cc00834346862a2847149d96265a5a19b1e555aa6425a9995217ebf038d2de9'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198501-198512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198501-198512.nc' 'SHA256' '55d28e321376bc81466adfd13fa5d1d8b5cd322863604dc8a39191c25889d723'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199001-199012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199001-199012.nc' 'SHA256' 'ef22c935f4ba4ac927e5b865f3d916284d387270f1aa7df43419637f4898f7d2'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198401-198412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198401-198412.nc' 'SHA256' '45c1ea5226f3ab148cbf573dcc45ea0d0aeae1ac775a6f1c8e5a5d478fdadb2a'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198901-198912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198901-198912.nc' 'SHA256' '4eee452e188536c33fcce61cec1719483e3f79d7ed186bc73e855e579d4e29a0'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201301-201312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201301-201312.nc' 'SHA256' '6056806a9d159694852fc8854564660e5674a8ba17356a001273f09824b868c7'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197001-197012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197001-197012.nc' 'SHA256' 'b69148deb0041ab12d490e633edd34ac497f6a1f0bc3a443eb6e962b7b35b6d9'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198101-198112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198101-198112.nc' 'SHA256' 'c0e5ad8c76d1916e8e11e259cf35b535f2586e9c8f32330d3bb62a39c0724520'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200301-200312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200301-200312.nc' 'SHA256' 'd64c885ffa053a13e8fed16bc9871cc41883d1e4827f554d9739c716f9685028'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198301-198312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198301-198312.nc' 'SHA256' 'cc00e9731bec599bdfda6901f9d05c3b762a96c18820faf92e39195033b8ca96'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201001-201012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201001-201012.nc' 'SHA256' 'e3890ae201f56145b78b59ce733fd7637474befc9a8bf2d9583f9e5a6e93e8d5'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201201-201212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201201-201212.nc' 'SHA256' '3a36be9d061cc7e2b61086078600ca5d9994db3381a1a2bac15282e1b068f6e7'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197201-197212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197201-197212.nc' 'SHA256' 'f369262f8636ec620fae279d7d3ecdf2a28945e865ef9f015137152afdfb3008'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197301-197312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197301-197312.nc' 'SHA256' 'efadd654790d9c13d220734c7aa5e625609e44cacb444c107328d4708589d96b'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199501-199512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199501-199512.nc' 'SHA256' 'c779854b6e656923afe53c7ea84204a62e99c491589b8526ea4e5b0a37e3aac3'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200601-200612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200601-200612.nc' 'SHA256' '878272c133d0f001204de3afd3ec25d85d05bc2352c889a217ba1ea9e642c594'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197101-197112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197101-197112.nc' 'SHA256' '78d2c0c31bc80688d4d5f63f219d8c18eb35bb1ab5609c89318ef531455d0cb8'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197801-197812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197801-197812.nc' 'SHA256' '6d23473ea5283f0b0b3930f616454875f3060ac3b7cce2945b7f300c3638ac66'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198801-198812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198801-198812.nc' 'SHA256' '1b581985074c21fb79a08513d6376d59a3bd6c6f3b2e12582092c7b61321c1d9'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200201-200212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200201-200212.nc' 'SHA256' '680bd5e932d65343f287ecfd7dc8cdb21ab7110028d9d130c477a4709f6dc1be'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198701-198712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198701-198712.nc' 'SHA256' 'e5ea5ed498ce3d719fd89edcb9cdd2f79983d58b2b19b85e505b2fd0999f25a4'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199801-199812.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199801-199812.nc' 'SHA256' '4cb37887b6e17ecff4d61ba2ef540ff43df35a2f604db375a3034ed55109ce6a'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198601-198612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198601-198612.nc' 'SHA256' '187eb0a9095e050f4bf732d7d6360e33d8821af349c194dd13029e7c528fda81'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200101-200112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200101-200112.nc' 'SHA256' 'fc9e9f09ade789cbaeee390da9de44cd98c803f073196c0a6ee5e9ff98132cdb'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201401-201412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201401-201412.nc' 'SHA256' '96bbf02f4f90a436812df00c063b0dd7c73d64e0acbdcaf4b02cea10a6adf55a'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197501-197512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197501-197512.nc' 'SHA256' '295c7eb593a89877ae4209d6b8627958fcaf29d1e9ff481db54078088b6143b1'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197901-197912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197901-197912.nc' 'SHA256' 'df05050f9b57bebdd484a12996e3d2a6bb874562c8415163f229f101e0160a3d'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197701-197712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197701-197712.nc' 'SHA256' '11bd335c704d981ef75147fd8976429fa737e74862943f62097943b1631c7673'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199601-199612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199601-199612.nc' 'SHA256' 'b4c8f4a2297207a48389dc5d81826e3e7eaa4145673b0ba91b33e9fc4b42e6ac'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199901-199912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199901-199912.nc' 'SHA256' '0f02d9cf76286f48f6b897a2adbc8247c25ab59a7a362208363e7f1d35577f5d'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201101-201112.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_201101-201112.nc' 'SHA256' '050fc40a300f750ab5dcb83532cf929a277c4f135a96ea5ae46c4667c41a84b2'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197601-197612.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_197601-197612.nc' 'SHA256' '1286e4f6458d8ce8503a710d5d97c2755f12b260c6dbd3287a3d495a6d173187'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198201-198212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_198201-198212.nc' 'SHA256' '08e64940c4f26dbeca4d1a4e03aa3513454c4a6e45a6dba5fc7faf201e6c9af0'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199301-199312.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199301-199312.nc' 'SHA256' '0c2a3d02fe2bab36ccc1eb1b632b37b3a47cee29cec3bc14a3e596fdffcc4964'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200901-200912.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200901-200912.nc' 'SHA256' 'a5caf6dcc8d86ddfda1ba8698be2e84f2f5fc631ea7d9c81dc16968aef74ce65'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199201-199212.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199201-199212.nc' 'SHA256' 'a03b6ac0ec08f1542aac56c1831dfa5d34b9c239fc7918efd38deb82bcf9cad2'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199401-199412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199401-199412.nc' 'SHA256' '36c39e33a1c9f7a54266d677b7b758ecff48b9691983024e11ade32369a3136b'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200401-200412.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200401-200412.nc' 'SHA256' 'b75c920d940fb56a2a53782dce9e0f4b3b070b252242befafdfda36588c821b0'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200701-200712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200701-200712.nc' 'SHA256' '89e36205ac04997e84246978c7dd0fd4c6862ac53c9d5fd59c856f2adf15fed1'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199701-199712.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_199701-199712.nc' 'SHA256' '1321025f9b3ed3b8647dbcfe794aa08e2f37fb22e12284b7027aaad4521536a5'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200001-200012.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200001-200012.nc' 'SHA256' '72fca4a2e0c4a0ba80a8f9a1c7031da660a82e532455366286d918c19e44763e'
'hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200501-200512.nc' 'https://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r121i1p1f1/Amon/hus/gr/v20200412/hus_Amon_EC-Earth3_historical_r121i1p1f1_gr_200501-200512.nc' 'SHA256' '3603f6e02e4907f5dca6b620505ca329d2d360f77655756e9eda0d17c8e16b0d'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
