#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:52:51
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.Amon.rsdt.gr.v20200412|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198801-198812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198801-198812.nc' 'SHA256' 'ac4b2a25e59514aef5d2eaee1f47d467983c386112da371caffb09475fbd32aa'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200501-200512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200501-200512.nc' 'SHA256' 'a117ea7bee50bbe1d2984de39de35c06fdee7e537847665e899d7acb986feda4'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197301-197312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197301-197312.nc' 'SHA256' 'c4bd325878864b7228132d59b0555eeb17c9676e25016fceaaf36ee652c001db'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197701-197712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197701-197712.nc' 'SHA256' '05c1dba218637bba1fa38f3db87ae8addd1b2e22becff6b1ac60af493b4af186'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198401-198412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198401-198412.nc' 'SHA256' 'b81e5900149e775d54d2df7b7691b50bd03ac8cdf4871eb957b53c1011d28f6e'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200601-200612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200601-200612.nc' 'SHA256' 'd1546fddf45df12b3e23d90b955f48e8f59cf7bc999d15f977616e38d0084ac8'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201001-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201001-201012.nc' 'SHA256' '6af2725502bb2a6f334b41e52510ab0671338cd394c6b88704d021a0ad21f15c'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198901-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198901-198912.nc' 'SHA256' 'aa9a8aaa66876de1469dd7eb9f43e7098a15bb0abe77771c8188ae9c2f70696e'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199901-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199901-199912.nc' 'SHA256' '2863b8be3a42fec710e3528147fcceab3cf1de47f0f53fb2eb0a8cd7be83274b'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200801-200812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200801-200812.nc' 'SHA256' '4f3b8f4a4a9cf62edde77bf1f3fae6f8b826dc3d290805855ae5a83bf7ef5e2c'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197501-197512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197501-197512.nc' 'SHA256' '85ffc11047448bd6208d830aab88022e94ea7c2db5b34da5c90129375372aad8'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197801-197812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197801-197812.nc' 'SHA256' 'b3d12b12c85788d30012e6f23e9eec5b2acfd13725c5ac7548226c98a415e461'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198201-198212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198201-198212.nc' 'SHA256' '4eeff5e9f9c5cab4f15c10018a126d9fd75c473519c246c9ffb82543666896b6'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198301-198312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198301-198312.nc' 'SHA256' '2942cb3a78e2f9962b8fa715d6b6c388a73ba7bc0c832445ac7da7eaca51ec91'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198001-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198001-198012.nc' 'SHA256' 'd7cc12252b5e23175ba225957b693b9ee84141e50b0fdb541359ef0e8f2f7e2d'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199101-199112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199101-199112.nc' 'SHA256' 'ceed7cc2f08a79c9c8ebcb3c863b2b74812a77b67e41b0d420a804c0399f2d69'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199401-199412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199401-199412.nc' 'SHA256' '7fcb75d8182de99d38d0e2958ddb9211ee047ce92fe7de8f6f2dbce96627724a'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199701-199712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199701-199712.nc' 'SHA256' '4df2a2ee625b86165d3bbe420734f2d877b9909f358a357745f09dfdef2cee7c'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199801-199812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199801-199812.nc' 'SHA256' '88e3acb7b2921e7312164b1c4ef5d1cdae9efa38c5e55fa7be38a74a0410a075'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200201-200212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200201-200212.nc' 'SHA256' '7572695f56824a0fa5f25638ba58846e3fb8babda2ee4c8ca1e328efea44b5b8'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200301-200312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200301-200312.nc' 'SHA256' '8bc6bb5c28c089e8cee600bc786e4d11dd3e140578606a1457cf631b6edcf521'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201401-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201401-201412.nc' 'SHA256' 'a8dd9e827fcdb71d0d36560346682ebf825939b7c65bcd57a0e89f109ed19fa2'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198101-198112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198101-198112.nc' 'SHA256' '8d8e33815297066f4f4f603d8d6b72cd43a6d886f721a024ee26ac9c2a741dee'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199201-199212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199201-199212.nc' 'SHA256' 'e71362a97633dbc418f82bf62a8fe92105465353a6a1dbf4833fb4b1b1633be1'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197201-197212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197201-197212.nc' 'SHA256' '86e40646d92b251fe8cc22954da732753d2c211047d8fd4c27cd240786117f9c'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197601-197612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197601-197612.nc' 'SHA256' '9d775e2c40c56634ab4c1507c727136c9c70746602e76e2db19ac7fedc8c624d'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200901-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200901-200912.nc' 'SHA256' 'aaca698ec04757cd9e10f20ad3dba21693a9b6d13ea933f70b3ea0278e4391c2'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198601-198612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198601-198612.nc' 'SHA256' '6456726905bb572301e8ce9bbb36b26ab80dcbcb9ca51760d20394fe99b8b9e5'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198701-198712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198701-198712.nc' 'SHA256' 'a71a4ceffdb39a44dc6bd4d7f263c75a1929dad4f56953440994aa8e5cf39ddb'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197101-197112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197101-197112.nc' 'SHA256' '43129ce44d1a4a83dfa52ee981e0bfc27793bcb54a7eba88ba05a4d37f4d151f'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200401-200412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200401-200412.nc' 'SHA256' '685e864b5302953a02b2329053464e29425c9ef4a774d6c543c7a208fb3a44e3'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201301-201312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201301-201312.nc' 'SHA256' '20b6c6b9ae9a6935db39dbacc104d832e9dfc182f2205e70f77ec649dea0df17'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197901-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197901-197912.nc' 'SHA256' '39eff15960979326ac6bea21dbc337b176c72a946b54b86239fe1677a2876900'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199601-199612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199601-199612.nc' 'SHA256' '7f12d4b8fee0d4a55d5458bbfa928f042505eb4dda99f3dde919399d64259799'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200101-200112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200101-200112.nc' 'SHA256' '0a1bde5416a51f1c59573c66ed5a0c965dff211c6ada0f0ed6c12e4c373b5236'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199301-199312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199301-199312.nc' 'SHA256' '25b00ab2ec6e05f9f367e300eeda6251874e6fdf3ce8b254c908f149bbec1ea2'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201101-201112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201101-201112.nc' 'SHA256' '636c2d77748f20174346aa3ddc289074c4f2789ec14ec0bf9491188a1e66f50c'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201201-201212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_201201-201212.nc' 'SHA256' 'aa6f0e60b9fa55460ec577ed113782798f1160b65d52746593b4e1698acc08d9'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197401-197412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197401-197412.nc' 'SHA256' 'a578594505d6b09cedb8660201e2d0777f014bf49d37933bc057b588486babac'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198501-198512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_198501-198512.nc' 'SHA256' '6bdd175e0e0f6a72ae9104d31a6452904ca3ae90cd74b4ffc5c1bd6ea4073da3'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200001-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200001-200012.nc' 'SHA256' '7cb41a3d9cb411f53a2750283491697f5460cc64ee004e512d41b178cb38759e'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200701-200712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_200701-200712.nc' 'SHA256' '16865ca296082cb0a77d7537c1cba70ec2ece27763d0d5d701f2e6e6a883af17'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197001-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_197001-197012.nc' 'SHA256' 'e4c1fc8126a2e26a29e0b96adf346407171d7ca8a64908ab1008d3d351f684c1'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199001-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199001-199012.nc' 'SHA256' '6f9a52300b4ad57e2f3e4d0b4aa6e12fb3a1c23423067eeef5df4de0e8ef6046'
'rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199501-199512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Amon/rsdt/gr/v20200412/rsdt_Amon_EC-Earth3_historical_r120i1p1f1_gr_199501-199512.nc' 'SHA256' '07a0690cbecafd6a0fa5de3df0688501bb824222b726e15f4bb37c6ee6d887e3'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
