#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/05/07 16:53:17
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3.historical.r120i1p1f1.Omon.uo.gn.v20200919|eagle.alcf.anl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198001-198012.nc' 'SHA256' '726c882576aa43c3b3c7e1b70415875499654191fb447daee60b2e9460e65e6e'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197701-197712.nc' 'SHA256' 'cb2ab6ffc57fae4636b3a995a86250cda2069ca294f6b27cf1932c5b8527976d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197801-197812.nc' 'SHA256' '5b64f5f6b8d2f5f733c64eb8fce7ba4a142566ac9a640cb7cb05803f50e9f662'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197901-197912.nc' 'SHA256' '1b25a95e429c119274b79cd5eebe269aa507eb6d5cc6152c9ebee07f1aba6a9b'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198601-198612.nc' 'SHA256' 'ca5db6adcc3ca412ab58d077668e2e941b4b05d4d97472ed02ebc887391a3c55'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200101-200112.nc' 'SHA256' '6a3db825de358f549b4aa263fe5783d43101ced7be95db086fa0eed603f51f4d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198401-198412.nc' 'SHA256' '93cb4def995baf9fe7f8e7b6c597dbc6cc214cf575af2bd6fe04e62e31e0d522'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200301-200312.nc' 'SHA256' '0e25b904ca4eb6899715347e2dd2e165391f0c61646906bc1f2f78dfcde016cb'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201101-201112.nc' 'SHA256' 'e47cb810acfbc3f78972e638bb7fcfe4cacc606f96ec52de7b86285137a8be6d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201401-201412.nc' 'SHA256' 'a3add4d73fff537c3bc60d92c66d4ad8c909265972e4a689165a14238483c353'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199501-199512.nc' 'SHA256' '089acc341bbcb78707f43ad37443b3a796e468c613c58aa63265708da3f81f1c'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200501-200512.nc' 'SHA256' 'eb36b87fcc97bb6c955ef5c1ad8f574e3da11cf0b884311451cd34917e6f0d20'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200701-200712.nc' 'SHA256' 'bc17bd4984ae52beacd08721b818d1c7191752bd1e3aaeb3e990d6a320718e7a'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201301-201312.nc' 'SHA256' '050b67b2a23f5f4f3b5e7e5e87f214ed428519804a0d3aa1afe436724b477bcb'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197501-197512.nc' 'SHA256' '9bbbec0923ce83dd2dce29d52fb13606ea9e3ab6f3d61dc240b2089057ce70e1'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199001-199012.nc' 'SHA256' 'bb429b8d06398d8b3a04f4482743f771e262976fec07631ed148d891b7c3a1c1'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200401-200412.nc' 'SHA256' 'fa498ff412fcc0bfa43be7355c63531392ac2b95b0b0c7c62f93e41b4de73692'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197101-197112.nc' 'SHA256' '904105d4f14bbc4b3cd67b7ff7f834194a90fcc0661c89d4161b943833abecaa'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199301-199312.nc' 'SHA256' 'b35288bb30c8b77f80b39f1a22800c9e7ffa9845a4b5e3b0911a0a26d36bd34d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200801-200812.nc' 'SHA256' 'a47b7bde62c526aefb02724a2d42a121f769f98667c6e9eb50c50c14d515b44f'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201201-201212.nc' 'SHA256' '51b283ad97eca93811db9063e44a2e2edd2b5ee6039e9509b4fe7c0a4b8df881'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198301-198312.nc' 'SHA256' '9e6678923c1f0af022debaff0d48431142c65f84fdf7bcb9a3912d4a4565e42d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199801-199812.nc' 'SHA256' '1d84619ff43beeb097cffb77aaa5e626f6194d74e0b38de7f940cd72762f5499'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200001-200012.nc' 'SHA256' '698a9e7b1616e79eccfc747bb91678c77bfe02cc7da45a308115ca2d5bdda366'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197001-197012.nc' 'SHA256' '0252ec80a7eb011a87d547da9fb44032f212f6ce012ab4b5b7e52dbf1812f365'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198201-198212.nc' 'SHA256' '14a511b3151c5b24a5212fd396a7f63813ca75dcb18bd434341825f2b0fa7fbf'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198901-198912.nc' 'SHA256' 'b43b0b7f264e506564ccb5672645691e91631565dffcc485a6d25431f4173e2c'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197601-197612.nc' 'SHA256' '1513c2cc82b2594c27c943f10060db849c25846424a8b5122be0c83e1e772f07'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198501-198512.nc' 'SHA256' 'f712400ef8356a4e24e7fa46571587f07b9517e6062fa367c215c0dfb3dc01f0'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199901-199912.nc' 'SHA256' '0ba3a62f91344f5798d29db581de91880c2604874f2101695b2524002d702eff'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197301-197312.nc' 'SHA256' 'a88ad1bb906e4d2031ba2729510775ea3831dd3156f462fbae3e5353d73280ae'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197401-197412.nc' 'SHA256' 'a0105f76590a76786a89bea971300e8c1455bbe5932d7092c02638755de63379'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198101-198112.nc' 'SHA256' '1401683c979670673267b178040ef1bb4763a6b4e783f118107583e117c516ae'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198701-198712.nc' 'SHA256' 'e22c9f82f8943ee108d108ee90c4a2f034e45e7401d0ec2494070a385d92705b'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199101-199112.nc' 'SHA256' '732d2843b358478c873ea7207fef275016c6178745f463b87b1b9f8cadb9bbfc'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199401-199412.nc' 'SHA256' '76a7c9bbc278eee850d74a99d4c579dc50b2d51fae0184ec1a968f0765d9ce37'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200901-200912.nc' 'SHA256' 'e0a411823eaba49fb08158cf27a363f3ce1c3a835c34106a1cf464b1ec6779d5'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199601-199612.nc' 'SHA256' '53c0d680c55daf3ac9d8ccad295eef032f59fb9d61fd1bad2e18abcb8e26f122'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_197201-197212.nc' 'SHA256' 'db0cae36cd683c26412c4d2bdfa204e671fc2dca1208c732bd30ce051c7f3d6f'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200201-200212.nc' 'SHA256' '8bfaa01d85a142a8335beb6e6635e2cf5aa2e07fb8b9274f4e59f4b29a57e728'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_198801-198812.nc' 'SHA256' '9f68792d1c622c96c31d5e20b839bd882675537e6cb869e55c3f8631a6dffa5d'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199201-199212.nc' 'SHA256' '28ea624d71fdb04556119a01dff5540c328615223cd4f4f0f3d5a131c2611f3b'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_201001-201012.nc' 'SHA256' 'ad30223835db24bb3fddd48ce84bf82a38b6dd454a25f48863fa41eda79934bc'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_199701-199712.nc' 'SHA256' 'efe72cf9e531f2b42a3a22d4856ffad091753464dee4f5e4ceb7ce4e020f594e'
'uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'https://g-52ba3.fd635.8443.data.globus.org/css03_data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r120i1p1f1/Omon/uo/gn/v20200919/uo_Omon_EC-Earth3_historical_r120i1p1f1_gn_200601-200612.nc' 'SHA256' '2ac9ce21d95b22b6f1599765c8c4cad85e99ea2caed2b3565dd3614c9cc9a7f4'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 45 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
